/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import domain.Agent;
import domain.Angazovanje;
import domain.Menadzer;
import domain.Ugovor;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.controller.Controller;

/**
 *
 * @author Korisnik
 */
public class FrmCreateAngažovanje extends javax.swing.JPanel {

    /**
     * Creates new form FrmCreateAngažovanje
     */
    private Menadzer menadzer;
    public FrmCreateAngažovanje(Menadzer menadzer) throws Exception {
        System.out.println("U konstruktoru create angazovanje fomre.");
        initComponents();
        this.menadzer = menadzer;
        popuniFormuPodacima();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMenadzer = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRedniBrojAngazovanja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProvizija = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRealizovano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbUgovori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbAgent = new javax.swing.JComboBox<>();
        btnOdustani = new javax.swing.JButton();
        btnStatistika = new javax.swing.JButton();

        jLabel1.setText("Menadžer:");

        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel2.setText("Redni broj angažovanja:");

        jLabel3.setText("Provizija:");

        jLabel4.setText("Realizovano:");

        jLabel5.setText("Ugovor:");

        jLabel6.setText("Agent:");

        btnOdustani.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnStatistika.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnStatistika.setText("Statistika agenata");
        btnStatistika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvaj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRedniBrojAngazovanja)
                            .addComponent(txtMenadzer)
                            .addComponent(txtProvizija)
                            .addComponent(txtRealizovano)
                            .addComponent(cbUgovori, 0, 450, Short.MAX_VALUE)
                            .addComponent(cbAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOdustani)
                        .addGap(119, 119, 119)
                        .addComponent(btnStatistika)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRedniBrojAngazovanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProvizija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRealizovano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOdustani)
                    .addComponent(btnStatistika))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        // TODO add your handling code here:
        
          this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            // TODO add your handling code here:
            double provizija = Double.parseDouble(txtProvizija.getText());
            long redniBroj = Long.parseLong(txtRedniBrojAngazovanja.getText());
            boolean realizovano = false;
            if(txtRealizovano.getText().equals("DA")){
                realizovano=true;
            }else{
                realizovano = false;
            }
            Agent a = (Agent) cbAgent.getSelectedItem();
            Ugovor u = (Ugovor) cbUgovori.getSelectedItem();
            Angazovanje angažovanje = new Angazovanje(redniBroj,provizija,realizovano,u,a, menadzer);
            boolean signal = Controller.getInstance().createAngazovanje(angažovanje);
            if(signal){
                JOptionPane.showMessageDialog(this, "Sistem je uspešno uneo angažovanje.","Unos angažovanja",JOptionPane.INFORMATION_MESSAGE);
                this.getTopLevelAncestor().setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da unese angažovanje.","Unos angažovanja",JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmCreateAngažovanje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnStatistikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikaActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog((JFrame)null, "Statistika agenata", true); //na dijalog dodacu panel
          JPanel panel = new StatistikaAgenata();
          dialog.add(panel); // dodajem panel na dijalog
          dialog.pack(); //napakovati panel na dijalog 
          dialog.setLocationRelativeTo(null); // bice na sredini
          dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
          dialog.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnStatistikaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnStatistika;
    private javax.swing.JComboBox<Object> cbAgent;
    private javax.swing.JComboBox<Object> cbUgovori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMenadzer;
    private javax.swing.JTextField txtProvizija;
    private javax.swing.JTextField txtRealizovano;
    private javax.swing.JTextField txtRedniBrojAngazovanja;
    // End of variables declaration//GEN-END:variables

    private void popuniFormuPodacima() throws Exception {
        System.out.println("Usao u popuni formu podacima");
        
         txtMenadzer.setText(menadzer.getImeMenadzera()+" "+menadzer.getPrezimeMenadzera());
        txtMenadzer.setEnabled(false);
        
        
        System.out.println("Setova txtMenadzer i onemogucio izmenu");
        
        
        
        List<Agent> agenti = Controller.getInstance().getAllAgenti();
        System.out.println("Vratio listu agenata iz baze");
        for (Agent a: agenti){
            cbAgent.addItem(a);
        }
        
        
        List<Ugovor> ugovori = Controller.getInstance().getAllUgovori();
        
        for(Ugovor u: ugovori){
            cbUgovori.addItem(u);
        }
        
        
    }
}
