/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import domain.Klijent;
import domain.TipKlijenta;
import domain.Ugovor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.controller.Controller;
import ui.forms.tables.ModelTabeleAgent;
import ui.forms.tables.ModelTabeleUgovor;

/**
 *
 * @author Korisnik
 */
public class FrmNoviKlijent extends javax.swing.JPanel {

    /**
     * Creates new form FrmNoviKlijent
     */
    private Klijent klijent;
    private List<Ugovor> ugovori;
    
    public FrmNoviKlijent() throws Exception {
        initComponents();
        popuniCbTipKlijenta();
        kreirajModelTabeleUgovor();
        this.klijent = new Klijent();
        this.ugovori = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJMBGKlijenta = new javax.swing.JTextField();
        txtImeKlijenta = new javax.swing.JTextField();
        txtPrezimeKlijenta = new javax.swing.JTextField();
        cbTipKlijenta = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBrojUgovora = new javax.swing.JTextField();
        txtAdresaNekretnine = new javax.swing.JTextField();
        txtPovrsinaNepokretnosti = new javax.swing.JTextField();
        txtSprat = new javax.swing.JTextField();
        txtDatumZakljucenja = new javax.swing.JTextField();
        btnDodajUgovor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUgovori = new javax.swing.JTable();
        btnObrisiUgvoor = new javax.swing.JButton();

        jLabel1.setText("JMBG klijenta:");

        jLabel2.setText("Ime klijenta:");

        jLabel3.setText("Prezime klijenta:");

        jLabel4.setText("Tip klijenta:");

        txtPrezimeKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeKlijentaActionPerformed(evt);
            }
        });

        cbTipKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipKlijentaActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnPonisti.setText("Poništi");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        jLabel6.setText("Unesite adresu nekretnine:");

        jLabel7.setText("Unesite površinu:");

        jLabel8.setText("Unesite sprat:");

        jLabel5.setText("Unesite broj ugovora:");

        jLabel9.setText("Unesite datum zaključenja:");

        txtBrojUgovora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojUgovoraActionPerformed(evt);
            }
        });

        txtSprat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpratActionPerformed(evt);
            }
        });

        txtDatumZakljucenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumZakljucenjaActionPerformed(evt);
            }
        });

        btnDodajUgovor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDodajUgovor.setText("dodaj ugovor");
        btnDodajUgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUgovorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDatumZakljucenja, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(txtSprat)
                            .addComponent(txtBrojUgovora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdresaNekretnine, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPovrsinaNepokretnosti, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(120, 120, 120))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodajUgovor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBrojUgovora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdresaNekretnine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtPovrsinaNepokretnosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSprat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtDatumZakljucenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodajUgovor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        tblUgovori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUgovori);

        btnObrisiUgvoor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnObrisiUgvoor.setText("Obriši ugovor");
        btnObrisiUgvoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUgvoorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(58, 58, 58))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJMBGKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrezimeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnObrisiUgvoor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnSacuvaj)
                        .addGap(347, 347, 347)
                        .addComponent(btnPonisti))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJMBGKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezimeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(btnObrisiUgvoor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnPonisti))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        /*
        String jmbg = txtJMBGKlijenta.getText();
        String ime = txtImeKlijenta.getText();
        String prezime = txtPrezimeKlijenta.getText();
        TipKlijenta tipKlijenta= (TipKlijenta)cbTipKlijenta.getSelectedItem();*/
        //List<Ugovor> ugovori = new ArrayList<>();
        
        /*
        long brojUgovora = Long.parseLong(txtBrojUgovora.getText());
        String adresaNekretnine = txtAdresaNekretnine.getText();
        double povrsinaNepokr = Double.parseDouble(txtPovrsinaNepokretnosti.getText());
        int sprat = Integer.parseInt(txtSprat.getText());
        String datumStr = txtDatumZakljucenja.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datumDate = null;
        try {
           datumDate = sdf.parse(datumStr);
        } catch (ParseException ex) {
            Logger.getLogger(FrmNoviKlijent.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.klijent = new Klijent(jmbg, ime, prezime, tipKlijenta, ugovori); //prazni ugovori
        Ugovor ugovor = new Ugovor(klijent, brojUgovora, adresaNekretnine, povrsinaNepokr, sprat, datumDate);
        klijent.dodajUgovor(ugovor);*/
        boolean signal=false;
        try {
            klijent.setUgovori(this.ugovori);
            signal = Controller.getInstance().createKlijent(klijent);
        } catch (Exception ex) {
            Logger.getLogger(FrmNoviKlijent.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (signal){
            JOptionPane.showMessageDialog(this,"Sistem je zapamtio klijenta","Novi klijent" , JOptionPane.INFORMATION_MESSAGE);
            this.getTopLevelAncestor().setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this,"Sistem ne može da zapamti klijenta","Novi klijent" , JOptionPane.WARNING_MESSAGE);
            this.getTopLevelAncestor().setVisible(false);
        
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        // TODO add your handling code here:
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void cbTipKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipKlijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipKlijentaActionPerformed

    private void txtPrezimeKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeKlijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeKlijentaActionPerformed

    private void txtSpratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpratActionPerformed

    private void txtBrojUgovoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojUgovoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojUgovoraActionPerformed

    private void btnDodajUgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUgovorActionPerformed
        // TODO add your handling code here:
        
        //1. kreira se novi klijent. 
        
        String jmbg = txtJMBGKlijenta.getText();
        System.out.println(jmbg);
        String ime = txtImeKlijenta.getText();
        System.out.println(ime);
        String prezime = txtPrezimeKlijenta.getText();
        System.out.println(prezime);
        TipKlijenta tipKlijenta= (TipKlijenta)cbTipKlijenta.getSelectedItem();
        System.out.println(tipKlijenta);
        
        this.klijent.setJmbgKlijenta(jmbg);
        this.klijent.setImeKlijenta(ime);
        this.klijent.setPrezimeKlijenta(prezime);
        this.klijent.setTipKlijenta(tipKlijenta);
        
        //2. kreira se novi ugovor
        
        Ugovor noviUgovor = new Ugovor(); 
        System.out.println("Kreirana je instanca novi ugovor");
        int brojUgovora = Integer.parseInt(txtBrojUgovora.getText());
        System.out.println("Ocitan je broj ugovora"+brojUgovora);
        
        String adresaNekretnine = txtAdresaNekretnine.getText();
        System.out.println(adresaNekretnine);
        double povrsinaNepokr = Double.parseDouble(txtPovrsinaNepokretnosti.getText());
        System.out.println(povrsinaNepokr);
        int sprat = Integer.parseInt(txtSprat.getText());
        System.out.println(sprat);
        String datumStr = txtDatumZakljucenja.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        System.out.println(datumStr);
        Date datumDate = null;
        try {
           datumDate = sdf.parse(datumStr);
        } catch (ParseException ex) {
            Logger.getLogger(FrmNoviKlijent.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(datumDate);
        noviUgovor.setBrojUgovora(brojUgovora);
        noviUgovor.setAdresaNekretnine(adresaNekretnine);
        noviUgovor.setDatumZakljucenja(datumDate);
        noviUgovor.setPovrsinaNepokretnosti(povrsinaNepokr);
        noviUgovor.setSprat(sprat);
        
        //3. setuje se klijent na ugovoru koji se odnosi na tog klijenta
        
        noviUgovor.setKlijent(this.klijent);
        System.out.println("NOVI UGOVOR: ");
        System.out.println(noviUgovor);
        //4. dodaje se ugovor na listu ugovora - ovo je lista ugovora koja se odnosi na tog klijenta
        
        this.ugovori.add(noviUgovor);
        tblUgovori.setModel(new ModelTabeleUgovor(this.ugovori));
        
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li želite da dodate još ugovora?","Dodavanje novog ugovora",JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION){
            txtBrojUgovora.setText("");
            txtBrojUgovora.setText("");
            txtDatumZakljucenja.setText("");
            txtSprat.setText("");
            txtAdresaNekretnine.setText("");
            txtPovrsinaNepokretnosti.setText("");
        }else{
           //5. vise nece da se dodaje ugvora za tog klijenta, pa cu da setujem njegovu listu ugovora
           this.klijent.setUgovori(this.ugovori);
           
           //6. dodati sve te ugovore u bazu-> to radi button Sačuvaj. sada su u ovoj formi sačuvani lista ugovora i klijent. 
        }
        
        
        
    }//GEN-LAST:event_btnDodajUgovorActionPerformed

    private void btnObrisiUgvoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUgvoorActionPerformed
        // TODO add your handling code here:
       ModelTabeleUgovor mtu = (ModelTabeleUgovor) tblUgovori.getModel();
       int selektovaniRed = tblUgovori.getSelectedRow();
       Ugovor u = mtu.getUgovori().get(selektovaniRed);
       mtu.removeUgovor(u);
       mtu.osvežiTabelu();
    }//GEN-LAST:event_btnObrisiUgvoorActionPerformed

    private void txtDatumZakljucenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumZakljucenjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumZakljucenjaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajUgovor;
    private javax.swing.JButton btnObrisiUgvoor;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cbTipKlijenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUgovori;
    private javax.swing.JTextField txtAdresaNekretnine;
    private javax.swing.JTextField txtBrojUgovora;
    private javax.swing.JTextField txtDatumZakljucenja;
    private javax.swing.JTextField txtImeKlijenta;
    private javax.swing.JTextField txtJMBGKlijenta;
    private javax.swing.JTextField txtPovrsinaNepokretnosti;
    private javax.swing.JTextField txtPrezimeKlijenta;
    private javax.swing.JTextField txtSprat;
    // End of variables declaration//GEN-END:variables

    private void popuniCbTipKlijenta() throws Exception {
        List<TipKlijenta> tipovi = Controller.getInstance().getAllTipKlijenta();
        for(TipKlijenta tip:tipovi){
            cbTipKlijenta.addItem(tip);
        }
    }

    private void kreirajModelTabeleUgovor() {
        this.ugovori = new ArrayList<>();
        tblUgovori.setModel(new ModelTabeleUgovor(this.ugovori));
    }
}
