/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import domain.Agent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.controller.Controller;
import ui.forms.tables.ModelTabeleAgent;

/**
 *
 * @author Korisnik
 */
public class PretragaAgenta extends javax.swing.JPanel {

    /**
     * Creates new form PretragaAgenta
     */
    public PretragaAgenta() {
        initComponents();
        tblAgenti.setModel(new ModelTabeleAgent(new ArrayList<>()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImeAgenta = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenti = new javax.swing.JTable();
        btnOdaberiAgenta = new javax.swing.JButton();

        jLabel1.setText("Ime agenta:");

        btnPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblAgenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAgenti);

        btnOdaberiAgenta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnOdaberiAgenta.setText("Odaberi agenta");
        btnOdaberiAgenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdaberiAgentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtImeAgenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btnOdaberiAgenta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImeAgenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnOdaberiAgenta)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            // TODO add your handling code here:
            String imeAgenta = txtImeAgenta.getText();
            List<Agent> agenti = Controller.getInstance().getAgenti(imeAgenta);
            ModelTabeleAgent mta = new ModelTabeleAgent(agenti);
            tblAgenti.setModel(mta);
            if(agenti.size()!=0){
                JOptionPane.showMessageDialog(this, "Sistem je našao agente po zadatoj vrednosti.", "Pretraga agenta",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Sistem ne može da nadje agente po zadatoj vrednosti.", "Pretraga agenta",JOptionPane.WARNING_MESSAGE);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(PretragaAgenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnOdaberiAgentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdaberiAgentaActionPerformed
        // TODO add your handling code here:
        int selektovaniRed = tblAgenti.getSelectedRow();
        if(selektovaniRed>=0){
//            JOptionPane.showMessageDialog(this, "Sistem je učitao agenta.", "Pretraga agenta",JOptionPane.INFORMATION_MESSAGE);
              ModelTabeleAgent mta = (ModelTabeleAgent) tblAgenti.getModel();
        Agent agent = mta.getAgenti().get(selektovaniRed);
        JDialog dialog = new JDialog((JFrame)null, "Selektovani agent", true); //na dijalog dodacu panel
        JPanel panel = new SelektovaniAgent(agent);
        dialog.add(panel); // dodajem panel na dijalog
        dialog.pack(); //napakovati panel na dijalog 
        dialog.setLocationRelativeTo(null); // bice na sredini
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.setVisible(true);
        //JOptionPane.showMessageDialog(this, "Sistem je učitao agenta.", "Pretraga agenta",JOptionPane.INFORMATION_MESSAGE);

        
        }
        
        else
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita agenta po zadatoj vrednosti.", "Pretraga agenta",JOptionPane.WARNING_MESSAGE);
       

                   
        
        
    }//GEN-LAST:event_btnOdaberiAgentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdaberiAgenta;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgenti;
    private javax.swing.JTextField txtImeAgenta;
    // End of variables declaration//GEN-END:variables
}
