/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import domain.Klijent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.controller.Controller;
import ui.forms.tables.ModelTabeleAgent;
import ui.forms.tables.ModelTabeleKlijent;

/**
 *
 * @author Korisnik
 */
public class PretragaKlijenta extends javax.swing.JPanel {

    /**
     * Creates new form PretragaKlijenta
     */
    List<Klijent> klijenti;
    public PretragaKlijenta() {
        initComponents();
        klijenti = new ArrayList<>();
        popuniModelTabeleKlijenti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImeKlijenta = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnOdaberi = new javax.swing.JButton();

        jLabel1.setText("Ime klijenta:");

        btnPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKlijenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKlijentiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKlijenti);

        btnOdaberi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnOdaberi.setText("Odaberi klijenta");
        btnOdaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnOdaberi)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnOdaberi)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            // TODO add your handling code here:
            String imeKlijenta = txtImeKlijenta.getText();
            System.out.println("POKUPIO JE IME KLIJENTA.");
            klijenti = Controller.getInstance().getKlijenti(imeKlijenta);
            if(klijenti.size()!=0)
                JOptionPane.showMessageDialog(this,"Sistem je našao klijente po zadatoj vrednosti", "Pretraga klijenata ", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Sistem ne može da nadje klijente po zadatoj vrednosti.", "Pretraga klijenta",JOptionPane.WARNING_MESSAGE);

            tblKlijenti.setModel(new ModelTabeleKlijent(klijenti));
        } catch (Exception ex) {
            Logger.getLogger(PretragaKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void tblKlijentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKlijentiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblKlijentiMouseClicked

    private void btnOdaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdaberiActionPerformed
        // TODO add your handling code here:
        int selektovaniRed= tblKlijenti.getSelectedRow();
        System.out.println("SEL RED: " + selektovaniRed);
        if(selektovaniRed==-1){
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita klijenta po zadatoj vrednosti. ", "Odabir klijenta", JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println("USAO JE U ELSE GRANU");
            ModelTabeleKlijent modelKlijent = (ModelTabeleKlijent)tblKlijenti.getModel();
            System.out.println("USPESNO JE IZVUKAO MODEL");
            Klijent selektovaniKlijent = modelKlijent.getKlijenti().get(selektovaniRed);
            System.out.println("IZVUKAO JE KLIJENTA IZ LISTE MODELA");
            //System.out.println(selektovaniKlijent);
            System.out.println(selektovaniKlijent.getImeKlijenta()+selektovaniKlijent.getPrezimeKlijenta()+selektovaniKlijent.getJmbgKlijenta()+selektovaniKlijent.getTipKlijenta());
            
            JDialog dialog = new JDialog((JFrame)null, "Klijent", true); //na dijalog dodacu panel
            JPanel panel = new SelektovaniKlijent(selektovaniKlijent);
            dialog.add(panel); // dodajem panel na dijalog
            dialog.pack(); //napakovati panel na dijalog 
            dialog.setLocationRelativeTo(null); // bice na sredini
            dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
            dialog.setVisible(true);
        }
        
    }//GEN-LAST:event_btnOdaberiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdaberi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtImeKlijenta;
    // End of variables declaration//GEN-END:variables

    private void popuniModelTabeleKlijenti() {
        tblKlijenti.setModel(new ModelTabeleKlijent(new ArrayList<>()));
    }
}
