/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import domain.Klijent;
import domain.TipKlijenta;
import domain.Ugovor;
import domain.UpdateKlijent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.controller.Controller;
import ui.forms.tables.ModelTabeleAgent;
import ui.forms.tables.ModelTabeleUgovor;

/**
 *
 * @author Korisnik
 */
public class SelektovaniKlijent extends javax.swing.JPanel {

    /**
     * Creates new form SelektovaniKlijent
     */
    Klijent klijent;
    Klijent noviKlijent;
    
    public SelektovaniKlijent(Klijent klijent) {
        initComponents();
        System.out.println("USAO JE U FORMU SELEKTIVani klijent" + klijent);
        this.klijent = klijent;
        this.noviKlijent = new Klijent();
        popuniPodatke(klijent);
        System.out.println("IZASAO JE IZ METODE KOJA POPUNJAVA PODATKE");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtJMBGKlijenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImeKlijenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrezimeKlijenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUgovori = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        cbTipKlijenta = new javax.swing.JComboBox<>();
        btnSacuvajIzmene = new javax.swing.JButton();

        jLabel1.setText("JMBG klijenta:");

        jLabel2.setText("Ime klijenta:");

        jLabel3.setText("Prezime klijenta:");

        jLabel4.setText("Tip klijenta:");

        tblUgovori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUgovori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUgovoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUgovori);

        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnNazad.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSacuvajIzmene.setText("Sačuvaj izmene");
        btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJMBGKlijenta)
                    .addComponent(txtImeKlijenta)
                    .addComponent(txtPrezimeKlijenta)
                    .addComponent(cbTipKlijenta, 0, 393, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnObrisi)
                .addGap(112, 112, 112)
                .addComponent(btnNazad)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJMBGKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezimeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTipKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi)
                    .addComponent(btnNazad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        txtImeKlijenta.setEnabled(true);
        txtPrezimeKlijenta.setEnabled(true);
        txtJMBGKlijenta.setEnabled(true);
        cbTipKlijenta.setEnabled(true);
        btnObrisi.setVisible(false);
        
        String ime = txtImeKlijenta.getText();
        String prezime = txtPrezimeKlijenta.getText();
        String jmbg = txtJMBGKlijenta.getText();
        TipKlijenta tipK = (TipKlijenta) cbTipKlijenta.getSelectedItem();
        
        Klijent noviKlijent = new Klijent(jmbg,ime,prezime,tipK);
        
        ModelTabeleUgovor mtu = (ModelTabeleUgovor) tblUgovori.getModel();
        List<Ugovor> ugovori = mtu.getUgovori();
        
        for(Ugovor u:ugovori){
            u.setKlijent(klijent);
        }
        
        noviKlijent.setUgovori(ugovori);
        this.noviKlijent = noviKlijent;
        
        
        
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void tblUgovoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUgovoriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUgovoriMouseClicked

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here: 
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIzmeneActionPerformed
        try {
            txtImeKlijenta.setEnabled(true);
        txtPrezimeKlijenta.setEnabled(true);
        txtJMBGKlijenta.setEnabled(true);
        cbTipKlijenta.setEnabled(true);
        btnObrisi.setVisible(false);
        
        String ime = txtImeKlijenta.getText();
        String prezime = txtPrezimeKlijenta.getText();
        String jmbg = txtJMBGKlijenta.getText();
        TipKlijenta tipK = (TipKlijenta) cbTipKlijenta.getSelectedItem();
        
        Klijent noviKlijent = new Klijent(jmbg,ime,prezime,tipK);
        
        ModelTabeleUgovor mtu = (ModelTabeleUgovor) tblUgovori.getModel();
        List<Ugovor> ugovori = mtu.getUgovori();
        
        for(Ugovor u:ugovori){
            u.setKlijent(klijent);
        }
        
        noviKlijent.setUgovori(ugovori);
        this.noviKlijent = noviKlijent;
            
            
            // TODO add your handling code here:
            //boolean signal = Controller.getInstance().createKlijent(klijent, klijent.getUgovori());
            System.out.println("SELEKTOVANI KLIJENT - NOVI KL JMBG - STARI KL JMBG"+noviKlijent.getJmbgKlijenta()+"  "+klijent.getJmbgKlijenta());
            UpdateKlijent uKlijent = new UpdateKlijent(noviKlijent,klijent.getJmbgKlijenta());
            boolean signal = Controller.getInstance().updateKlijent(uKlijent);
            if(signal){
                JOptionPane.showMessageDialog(this,"Sistem je uspešno izmenio klijenta.","Izmena klijenta", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this,"Sistem ne može uspešno da zapamti klijenta.","Izmena klijenta", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(SelektovaniKlijent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajIzmeneActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvajIzmene;
    private javax.swing.JComboBox<Object> cbTipKlijenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUgovori;
    private javax.swing.JTextField txtImeKlijenta;
    private javax.swing.JTextField txtJMBGKlijenta;
    private javax.swing.JTextField txtPrezimeKlijenta;
    // End of variables declaration//GEN-END:variables

    private void popuniPodatke(Klijent k) {
        
        try {
            txtImeKlijenta.setEnabled(false);
            txtPrezimeKlijenta.setEnabled(false);
            txtJMBGKlijenta.setEnabled(false);
            //txtTipKLijenta.setEnabled(false);
            System.out.println("USAO EJ U POPUNI PODATKE METODU"+k.getImeKlijenta());
            
            
            txtImeKlijenta.setText(k.getImeKlijenta());
            txtPrezimeKlijenta.setText(k.getPrezimeKlijenta());
            txtJMBGKlijenta.setText(k.getJmbgKlijenta());
            //txtTipKLijenta.setText(k.getTipKlijenta().getNazivTipa());
            tblUgovori.setModel(new ModelTabeleUgovor(k.getUgovori()));
            System.out.println("POPUNIO JE TEXT BOXOVE");
            
            
            List<TipKlijenta> tipoviKlijenata = Controller.getInstance().getAllTipKlijenta();
            for(TipKlijenta tipK : tipoviKlijenata){
                cbTipKlijenta.addItem(tipK);
            }
            cbTipKlijenta.setSelectedItem(klijent.getTipKlijenta());
            cbTipKlijenta.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Sistem je učitao klijenta.","Učitani klijent",JOptionPane.INFORMATION_MESSAGE);
        
        } catch (Exception ex) {
            Logger.getLogger(SelektovaniKlijent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
