/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import domain.Agent;
import domain.UpdateAgent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.controller.Controller;

/**
 *
 * @author Korisnik
 */
public class SelektovaniAgent extends javax.swing.JPanel {

    /**
     * Creates new form SelektovaniAgent
     */
    private Agent agent;
    public SelektovaniAgent(Agent agent) {
        initComponents();
        this.agent = agent;
        //JOptionPane.showMessageDialog(this, "Sistem je učitao agenta.", "Pretraga agenta",JOptionPane.INFORMATION_MESSAGE);

        popuniPodacima();
        //JOptionPane.showMessageDialog(this, "Sistem je učitao agenta.", "Pretraga agenta",JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBrojURegistru = new javax.swing.JTextField();
        txtImeAgenta = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtUspesnostRealizacije = new javax.swing.JTextField();
        txtBrojDodeljenihKlijenata = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAdresaAgenta = new javax.swing.JTextField();
        btnObrisi = new javax.swing.JButton();

        jLabel1.setText("Redni broj u registru posrednika:");

        jLabel2.setText("Ime agenta:");

        jLabel3.setText("Prezime agenta:");

        jLabel4.setText("Uspešnost realizacije:");

        jLabel5.setText("Broj dodeljenih klijenata:");

        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnNazad.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSacuvaj.setText("Sačuvaj ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel6.setText("Adresa agenta:");

        btnObrisi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnIzmeni))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBrojURegistru)
                                    .addComponent(txtImeAgenta)
                                    .addComponent(txtPrezime)
                                    .addComponent(txtUspesnostRealizacije)
                                    .addComponent(txtBrojDodeljenihKlijenata)
                                    .addComponent(txtAdresaAgenta, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnObrisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(btnNazad))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrojURegistru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImeAgenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtUspesnostRealizacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtBrojDodeljenihKlijenata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAdresaAgenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnNazad)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        txtBrojURegistru.setEnabled(true);
        txtImeAgenta.setEnabled(true);
        txtPrezime.setEnabled(true);
        txtAdresaAgenta.setEnabled(true);
        txtUspesnostRealizacije.setEnabled(true);
        txtBrojDodeljenihKlijenata.setEnabled(true);  
        btnObrisi.setVisible(false);
        
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            // TODO add your handling code here:
            long broj=Long.parseLong(txtBrojURegistru.getText());
            String ime = txtImeAgenta.getText();
            String prezime = txtPrezime.getText();
            String adresa = txtAdresaAgenta.getText();
            double uspesnost = Double.parseDouble(txtUspesnostRealizacije.getText());
            int brojDodeljenih=Integer.parseInt(txtBrojDodeljenihKlijenata.getText());
            Agent noviAgent = new Agent(broj,ime,prezime,adresa,uspesnost,brojDodeljenih);
            UpdateAgent updAgent = new UpdateAgent(noviAgent, agent.getRedniBrojURegistruPosrednika());
            boolean signal = Controller.getInstance().updateAgent(updAgent);
            if(signal){
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio agenta.", "Izmena agenta", JOptionPane.INFORMATION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti agenta.", "Izmena agenta", JOptionPane.WARNING_MESSAGE);
           
            }
        } catch (Exception ex) {
            Logger.getLogger(SelektovaniAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            // TODO add your handling code here:
            btnIzmeni.setVisible(false);
            boolean signal = Controller.getInstance().deleteAgent(this.agent);
            if(signal){
                JOptionPane.showMessageDialog(this, "Sistem je izbrisao agenta.", "Brisanje agenta", JOptionPane.INFORMATION_MESSAGE);
                this.getTopLevelAncestor().setVisible(false);
            }else{
                  JOptionPane.showMessageDialog(this, "Sistem ne može da obriše agenta.", "Brisanje agenta", JOptionPane.INFORMATION_MESSAGE);
           
            }
            
        } catch (Exception ex) {
            Logger.getLogger(SelektovaniAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAdresaAgenta;
    private javax.swing.JTextField txtBrojDodeljenihKlijenata;
    private javax.swing.JTextField txtBrojURegistru;
    private javax.swing.JTextField txtImeAgenta;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUspesnostRealizacije;
    // End of variables declaration//GEN-END:variables

    private void popuniPodacima() {
        txtBrojURegistru.setText(""+this.agent.getRedniBrojURegistruPosrednika());
        txtImeAgenta.setText(agent.getImeAgenta());
        txtPrezime.setText(agent.getPrezimeAgenta());
        txtAdresaAgenta.setText(agent.getAdresaAgenta());
        txtUspesnostRealizacije.setText(""+agent.getUspesnostRealizacije());
        txtBrojDodeljenihKlijenata.setText(""+agent.getBrojDodeljenihKlijenata());
        
        txtBrojURegistru.setEnabled(false);
        txtImeAgenta.setEnabled(false);
        txtPrezime.setEnabled(false);
        txtAdresaAgenta.setEnabled(false);
        txtUspesnostRealizacije.setEnabled(false);
        txtBrojDodeljenihKlijenata.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Sistem je učitao agenta.", "Pretraga agenta",JOptionPane.INFORMATION_MESSAGE);

    }
}
